version: "3"

services:

  # Process that manages the job queue & result queue
  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  # The process that takes jobs, runs code in
  # containers, and puts it on the result queue
  worker:
    image: worker
    restart: on-failure
    depends_on:
      - rabbitmq
    # Allow access to docker daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # The process that listens for test requests to
  # put on the job queue, and caches results to
  # serve to the client.
  producer:
    image: producer
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - 8080:8080
